services:
  # Backend API Service
  - type: web
    name: fleetlink-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/vehicles

  # Frontend Static Site
  - type: web
    name: fleetlink-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://fleetlink-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /api/*
        destination: https://fleetlink-backend.onrender.com/api/*
